server {

  location /featureserver/ {
    proxy_pass http://pg-feat-arches-search:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-arches-search:7800/tileserver/;
  }

  location / {
    proxy_pass http://arches-search:8000/;
  }

}