server {

  location /featureserver/ {
    proxy_pass http://pg-feat-arches-her:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-arches-her:7800/tileserver/;
  }

  location / {
    proxy_pass http://arches-her:8000/;
  }

}