
services:
    arches-her-c0d8d:
      container_name: arches-her-c0d8d
      image: he/arches_her-c0d8d:base
      build:
        args:
          - "PROJ_NAME=arches_her"
          - "PROJ_REPO_NAME=arches-her"
          - "DOCKER_PATH=./1.1/.ac_arches_her/docker"
        context: ../..
        dockerfile: ./1.1/.ac_arches_her/Dockerfile
        target: base
      command: create_project
      volumes:
        - ../..:/web_root
      env_file:
        - ./docker/env_file.env
      ports:
        - 8002:8000
        - 5678:5678
      stdin_open: true
      tty: true
