
services:
    arches-her-c0d8d:
      container_name: arches-her-c0d8d
      image: he/arches_her-c0d8d:dev_build
      build:
        args:
          - "PROJ_NAME=arches_her"
          - "PROJ_REPO_NAME=arches-her"
          - "DOCKER_PATH=./1.1/.ac_arches_her/docker"
        context: ../..
        dockerfile: ./1.1/.ac_arches_her/Dockerfile
        target: dev
      command: run_arches
      volumes:
        - ../../arches:/web_root/arches
        - ../../arches-her:/web_root/arches_her
        - ./docker:/web_root/docker
        - ../../arches-her-package:/web_root/arches_her_package
        - ../../arches-her-data:/web_root/arches_her_data
      env_file:
        - ./docker/env_file.env
      ports:
        - 8002:8000
        - 5678:5678
      stdin_open: true
      tty: true
    
    ## - possible 
    #arches-her-bash:
    #  profiles:
    #    - livereload
    #  container_name: arches-her-bash
    #  image: he/arches_her:dev_build
    #  command: ["bash"]
    #  volumes:
    #    - ../../arches:/web_root/arches
    #    - ../../arches-her:/web_root/arches_her
    #    - ./docker:/web_root/docker
    #    - ../../arches-her-package:/web_root/arches_her_package
    #    - ../../arches-her-data:/web_root/arches_her_data
    #  env_file:
    #    - ./docker/env_file.env
    #  ports:
    #    - 35729:35729      
    #  depends_on:
    #      - arches-her-c0d8d
    #  stdin_open: true
    #  tty: true

    arches-her-c0d8d-livereload:
      profiles:
        - livereload
      container_name: arches-her-c0d8d-livereload
      image: he/arches_her-c0d8d:dev_build
      command: run_livereload
      volumes:
        - ../../arches:/web_root/arches
        - ../../arches-her:/web_root/arches_her
      env_file:
        - ./docker/env_file.env
      ports:
        - 35729:35729      
      depends_on:
          - arches-her-c0d8d
      stdin_open: true
      tty: true
    
    arches-her-c0d8d-webpack:
      container_name: arches-her-c0d8d-webpack
      image: he/arches_her-c0d8d:dev_build
      command: run_webpack
      volumes:
        - ../../arches:/web_root/arches
        - ../../arches-her:/web_root/arches_her
      env_file:
        - ./docker/env_file.env
      ports:
        - 8028:8021
      depends_on:
          - arches-her-c0d8d
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches-her-c0d8d-network

volumes:
    arches-log-c0d8d:
    arches-static-c0d8d:
