
services:
    nginx-arches-her-c0d8d:
      container_name: nginx-arches-her-c0d8d
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./docker/nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - arches-her-c0d8d-network

    db-arches-her-c0d8d:
      container_name: db-arches-her-c0d8d
      image: postgis/postgis:14-3.2
      volumes:
        - ../../arches_her-postgres-data:/var/lib/postgresql/data
        - ../../arches_her-postgres-log:/var/log/postgresql
        - ./docker/init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '5433:5432'
      env_file: 
        - ./docker/env_file.env
      networks:
        - arches-her-c0d8d-network

    elastic-bindmount-init-arches-her-c0d8d:
      image: alpine
      container_name: elastic-bindmount-init-arches-her-c0d8d
      restart: "no"
      entrypoint: |
        /bin/sh -c "chown 1000:1000 /esBindMount"
      volumes:
        - ../../arches_her-elasticsearch-data:/esBindMount


    elasticsearch-arches-her-c0d8d:
      container_name: elasticsearch-arches-her-c0d8d
      image: elasticsearch:8.5.0
      volumes:
        #- ../../elasticsearch_data_arches_her:/usr/share/elasticsearch/data
        - ../../arches_her-elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
        - "9301:9300"
      env_file: 
        - ./docker/env_file.env
      networks:
        - arches-her-c0d8d-network
      depends_on:
        - elastic-bindmount-init-arches-her-c0d8d

    rabbitmq-arches-her-c0d8d:
      container_name: rabbitmq-arches-her-c0d8d
      image: rabbitmq:3.8-management
      hostname: my-rabbit
      volumes:
        - rabbitmq-data-c0d8d:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rabbitmq-logs-c0d8d:/var/log/rabbitmq/log
      ports:
        - 5673:5672
        - 15673:15672
      networks:
        - arches-her-c0d8d-network

    #pg-feat-arches-her:
    #  container_name: pg-feat-arches-her
    #  image: pramsey/pg_featureserv
    #  volumes:
    #    - ../../pg_featureserv_config_arches_her:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-arches-her:5432/arches_her
    #  ports:
    #    - 9000:9000
    #  networks:
    #    - arches-her-network
    #  depends_on:
    #    - db-arches-her
    
    #pg-tile-arches-her:
    #  container_name: pg-tile-arches-her
    #  image: pramsey/pg_tileserv
    #  volumes:
    #    - ../../pg_tileserv_config_arches_her:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-arches-her:5432/arches_her
    #  ports:
    #    - 7800:7800
    #  networks:
    #    - arches-her-network
    #  depends_on:
    #    - db-arches-her


networks:
  arches-her-c0d8d-network:
    name: arches-her-c0d8d-network
    driver: bridge

volumes:
    rabbitmq-logs-c0d8d:
    rabbitmq-data-c0d8d:
